**numpy**

In [18]:
import numpy as np

array creation

In [19]:
arr = np.array([[1, 2, 3, 4]])
#dtype=np.int16 to limit int size

In [20]:
arr

array([[1, 2, 3, 4]])

In [21]:
zeros=np.zeros((2,5))

In [22]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
rng = np.arange((15))

In [24]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
lspace=np.linspace(1,10,5)
#5 linerly spaced element from 1 to 10

In [34]:
lspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [45]:
emp=np.empty((2,3))

In [46]:
emp

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
emp_like=np.empty_like(lspace)

In [48]:
emp_like

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [49]:
ide=np.identity(10)

In [50]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

use

In [25]:
arr[0,1]

np.int64(2)

In [26]:
arr.shape

(1, 4)

In [27]:
arr.dtype

dtype('int64')

In [28]:
arr[0,1]=30

In [29]:
arr[0,1]

np.int64(30)

methods

In [54]:
arr1 =rng.reshape(3,5)
#changes shape and returns new array

In [55]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
arr1=arr1.ravel()
#converts to 1d array

In [57]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Axis

↓ axis 0
-> axis 1

In [59]:
arr=np.arange(9)
arr=arr.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
arr.sum(axis=0)

array([ 9, 12, 15])

In [61]:
arr.sum(axis=1)

array([ 3, 12, 21])

In [62]:
arr.T
#Transpose

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [64]:
#iterator
print(arr)
for i in arr.flat:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
0
1
2
3
4
5
6
7
8


In [66]:
arr.ndim
#dimension

2

In [68]:
arr.size

9

In [69]:
arr.nbytes
#total bytes consumed

72

In [ ]:
arr.argmax()
#max element index converts to 1d first

np.int64(8)

In [74]:
arr.argmax(axis=0)

array([2, 2, 2])

In [ ]:
arr.argmin()
#min element index converts to 1d first

np.int64(0)

In [ ]:
arr.argsort()
#array of indices in increasing order

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [75]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
arr1=np.array([[10, 13, 22],
       [31, 14, 25],
       [36, 7, 18]])
arr1

array([[10, 13, 22],
       [31, 14, 25],
       [36,  7, 18]])

In [77]:
arr1+arr

array([[10, 14, 24],
       [34, 18, 30],
       [42, 14, 26]])

In [78]:
arr1*5

array([[ 50,  65, 110],
       [155,  70, 125],
       [180,  35,  90]])

In [79]:
np.sqrt(arr1)

array([[3.16227766, 3.60555128, 4.69041576],
       [5.56776436, 3.74165739, 5.        ],
       [6.        , 2.64575131, 4.24264069]])

In [81]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
arr.min()

np.int64(0)

In [83]:
arr.sum()

np.int64(36)

In [85]:
arr.max()

np.int64(8)

In [87]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.where(arr>5)
#return cordinater x in first array y in second array

(array([2, 2, 2]), array([0, 1, 2]))

In [89]:
np.count_nonzero(arr)

np.int64(8)

In [90]:
np.nonzero(arr)

(array([0, 0, 1, 1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2, 0, 1, 2]))